/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BlockHashStoreInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "getBlockhash(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBlockhash",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBlockhash",
    data: BytesLike
  ): Result;

  events: {};
}

export class BlockHashStoreInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BlockHashStoreInterfaceInterface;

  functions: {
    getBlockhash(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getBlockhash(uint256)"(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getBlockhash(
    number: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getBlockhash(uint256)"(
    number: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getBlockhash(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getBlockhash(uint256)"(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getBlockhash(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBlockhash(uint256)"(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBlockhash(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBlockhash(uint256)"(
      number: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
