/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PoolHelperInterface extends ethers.utils.Interface {
  functions: {
    "averageFeesPerBlockEpoch(YGYStorageV1)": FunctionFragment;
    "averageFeesPerBlockSinceStart(YGYStorageV1)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "averageFeesPerBlockEpoch",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "averageFeesPerBlockSinceStart",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "averageFeesPerBlockEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "averageFeesPerBlockSinceStart",
    data: BytesLike
  ): Result;

  events: {};
}

export class PoolHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PoolHelperInterface;

  functions: {
    averageFeesPerBlockEpoch(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { averagePerBlock: BigNumber }>;

    "averageFeesPerBlockEpoch(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { averagePerBlock: BigNumber }>;

    averageFeesPerBlockSinceStart(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { averagePerBlock: BigNumber }>;

    "averageFeesPerBlockSinceStart(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { averagePerBlock: BigNumber }>;
  };

  averageFeesPerBlockEpoch(
    _storage: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "averageFeesPerBlockEpoch(YGYStorageV1)"(
    _storage: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  averageFeesPerBlockSinceStart(
    _storage: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "averageFeesPerBlockSinceStart(YGYStorageV1)"(
    _storage: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    averageFeesPerBlockEpoch(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "averageFeesPerBlockEpoch(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    averageFeesPerBlockSinceStart(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "averageFeesPerBlockSinceStart(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    averageFeesPerBlockEpoch(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "averageFeesPerBlockEpoch(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    averageFeesPerBlockSinceStart(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "averageFeesPerBlockSinceStart(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    averageFeesPerBlockEpoch(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "averageFeesPerBlockEpoch(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    averageFeesPerBlockSinceStart(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "averageFeesPerBlockSinceStart(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
