/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface StorageLibraryInterface extends ethers.utils.Interface {
  functions: {
    "poolLength(YGYStorageV1)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "poolLength", values: [string]): string;

  decodeFunctionResult(functionFragment: "poolLength", data: BytesLike): Result;

  events: {};
}

export class StorageLibrary extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: StorageLibraryInterface;

  functions: {
    poolLength(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "poolLength(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  poolLength(_storage: string, overrides?: CallOverrides): Promise<BigNumber>;

  "poolLength(YGYStorageV1)"(
    _storage: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    poolLength(_storage: string, overrides?: CallOverrides): Promise<BigNumber>;

    "poolLength(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    poolLength(_storage: string, overrides?: CallOverrides): Promise<BigNumber>;

    "poolLength(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    poolLength(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "poolLength(YGYStorageV1)"(
      _storage: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
