/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface VRFInterface extends ethers.utils.Interface {
  functions: {
    "PROOF_LENGTH()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "PROOF_LENGTH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PROOF_LENGTH",
    data: BytesLike
  ): Result;

  events: {};
}

export class VRF extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: VRFInterface;

  functions: {
    PROOF_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    "PROOF_LENGTH()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  PROOF_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  "PROOF_LENGTH()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    PROOF_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "PROOF_LENGTH()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    PROOF_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "PROOF_LENGTH()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PROOF_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PROOF_LENGTH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
