/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { StorageLibrary } from "../StorageLibrary";

export class StorageLibrary__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<StorageLibrary> {
    return super.deploy(overrides || {}) as Promise<StorageLibrary>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StorageLibrary {
    return super.attach(address) as StorageLibrary;
  }
  connect(signer: Signer): StorageLibrary__factory {
    return super.connect(signer) as StorageLibrary__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StorageLibrary {
    return new Contract(address, _abi, signerOrProvider) as StorageLibrary;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract YGYStorageV1",
        name: "_storage",
        type: "YGYStorageV1",
      },
    ],
    name: "poolLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61010d610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80639bc76f43146038575b600080fd5b605b60048036036020811015604c57600080fd5b50356001600160a01b0316606d565b60408051918252519081900360200190f35b6000816001600160a01b031663b3944d526040518163ffffffff1660e01b815260040160206040518083038186803b15801560a757600080fd5b505afa15801560ba573d6000803e3d6000fd5b505050506040513d602081101560cf57600080fd5b50519291505056fea2646970667358221220cdecad14b4965238ea51663fee19ec1c2734747108aa16f78e357d022e002a1464736f6c634300060c0033";
