/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { VaultProxy } from "../VaultProxy";

export class VaultProxy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<VaultProxy> {
    return super.deploy(overrides || {}) as Promise<VaultProxy>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): VaultProxy {
    return super.attach(address) as VaultProxy;
  }
  connect(signer: Signer): VaultProxy__factory {
    return super.connect(signer) as VaultProxy__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VaultProxy {
    return new Contract(address, _abi, signerOrProvider) as VaultProxy;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_implementation",
        type: "address",
      },
      {
        internalType: "contract YGYStorageV1",
        name: "__storage",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600280546001600160a01b0319163317905561029d806100326000396000f3fe60806040526004361061002d5760003560e01c806313af403514610064578063485cc9551461009957610034565b3661003457005b6001546001600160a01b03163660008037600080366000845af43d6000803e80801561005f573d6000f35b3d6000fd5b34801561007057600080fd5b506100976004803603602081101561008757600080fd5b50356001600160a01b03166100d4565b005b3480156100a557600080fd5b50610097600480360360408110156100bc57600080fd5b506001600160a01b038135811691602001351661010d565b6002546001600160a01b031633146100eb57600080fd5b600280546001600160a01b0319166001600160a01b0392909216919091179055565b61012f6040518060600160405280602b815260200161023d602b913983610160565b600080546001600160a01b039283166001600160a01b03199182161790915560018054939092169216919091179055565b61021782826040516024018080602001836001600160a01b03168152602001828103825284818151815260200191508051906020019080838360005b838110156101b457818101518382015260200161019c565b50505050905090810190601f1680156101e15780820380516001836020036101000a031916815260200191505b5060408051601f198184030181529190526020810180516001600160e01b031663319af33360e01b179052935061021b92505050565b5050565b80516a636f6e736f6c652e6c6f67602083016000808483855afa505050505056fe73657474696e6720696d706c656d656e746174696f6e20616e642073746f72616765206c6f636174696f6ea26469706673582212201f6822e2e20fe2bd1c55b0b7f142404e24bd56321c6d6fe7e130ea323a1a80b664736f6c634300060c0033";
